services:
  browserless:
    image: browserless/chrome:${BROWSERLESS_TAG}
    container_name: browserless-chrome
    restart: unless-stopped
    environment:
      - MAX_CONCURRENT_SESSIONS=${BROWSERLESS_MAX_CONCURRENT}
      - QUEUE_LENGTH=${BROWSERLESS_QUEUE_LENGTH}
      - PREBOOT_CHROME=${BROWSERLESS_PREBOOT}
      - CHROME_REFRESH_TIME=${BROWSERLESS_REFRESH_INTERVAL}
      - ENABLE_DEBUGGER=${BROWSERLESS_ENABLE_DEBUGGER}
      - DEFAULT_BLOCK_ADS=${BROWSERLESS_BLOCK_ADS}
      - SCREEN_WIDTH=${BROWSERLESS_SCREEN_WIDTH}
      - SCREEN_HEIGHT=${BROWSERLESS_SCREEN_HEIGHT}
      - SCREEN_DEPTH=${BROWSERLESS_SCREEN_DEPTH}
      - TOKEN=${BROWSERLESS_TOKEN}
    ports:
      - "${BROWSERLESS_PORT}:3000"
      - "${BROWSERLESS_DEBUG_PORT}:9222"
    volumes:
      - ./logs:/home/browserless/logs
      - ./browserless-data:/data
    networks:
      - ${GRID_NETWORK}

networks:
  browserless:
    name: ${GRID_NETWORK}
    driver: bridge
