services:
  selenium-hub:
    image: selenium/hub:${SELENIUM_VERSION}
    container_name: selenium-hub
    restart: unless-stopped
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_REQUEST_TIMEOUT=${SE_SESSION_REQUEST_TIMEOUT}
      - SE_SESSION_TIMEOUT=${SE_SESSION_TIMEOUT}
      - SE_ENABLE_TRACING=true
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - ${GRID_NETWORK}
    volumes:
      - ./logs:/opt/selenium/logs

  chrome:
    image: selenium/node-chrome:${SELENIUM_VERSION}
    container_name: selenium-node-chrome
    restart: unless-stopped
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=${SE_NODE_OVERRIDE_MAX_SESSIONS}
      - SE_NODE_MAX_SESSIONS=${SE_NODE_MAX_SESSIONS}
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=${SCREEN_WIDTH}
      - SE_SCREEN_HEIGHT=${SCREEN_HEIGHT}
      - SE_SCREEN_DEPTH=${SCREEN_DEPTH}
      - SE_NODE_PUBLIC_URI=http://${PUBLIC_GRID_HOST}:${PUBLIC_NODE_PORT}
    ports:
      - "5900:5900"
      - "7900:7900"
    networks:
      - ${GRID_NETWORK}

  firefox:
    image: selenium/node-firefox:${SELENIUM_VERSION}
    container_name: selenium-node-firefox
    restart: unless-stopped
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=${SE_NODE_OVERRIDE_MAX_SESSIONS}
      - SE_NODE_MAX_SESSIONS=${SE_NODE_MAX_SESSIONS}
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=${SCREEN_WIDTH}
      - SE_SCREEN_HEIGHT=${SCREEN_HEIGHT}
      - SE_SCREEN_DEPTH=${SCREEN_DEPTH}
      - SE_NODE_PUBLIC_URI=http://${PUBLIC_GRID_HOST}:${PUBLIC_NODE_PORT}
    ports:
      - "5901:5900"
      - "7901:7900"
    networks:
      - ${GRID_NETWORK}

  edge:
    image: selenium/node-edge:${SELENIUM_VERSION}
    container_name: selenium-node-edge
    restart: unless-stopped
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=${SE_NODE_OVERRIDE_MAX_SESSIONS}
      - SE_NODE_MAX_SESSIONS=${SE_NODE_MAX_SESSIONS}
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=${SCREEN_WIDTH}
      - SE_SCREEN_HEIGHT=${SCREEN_HEIGHT}
      - SE_SCREEN_DEPTH=${SCREEN_DEPTH}
  - SE_NODE_PUBLIC_URI=http://${PUBLIC_GRID_HOST}:${PUBLIC_NODE_PORT}
    ports:
      - "5902:5900"
      - "7902:7900"
    networks:
      - ${GRID_NETWORK}

networks:
  selenium-grid:
    name: ${GRID_NETWORK}
    driver: bridge
